from . import db
from datetime import datetime

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(100), nullable=False)
    last_name = db.Column(db.String(100), nullable=False)
    company_name = db.Column(db.String(100), nullable=False, default='Recruiter')
    email = db.Column(db.String(120), unique=True, nullable=False)
    phone_number = db.Column(db.String(15), nullable=False)
    birthday = db.Column(db.String(10), nullable=False)
    password = db.Column(db.String(60), nullable=False)
    role = db.Column(db.String(20), nullable=False, default='recruiter')
    bio = db.Column(db.Text)
    skills = db.Column(db.Text)
    education = db.Column(db.Text)
    cv_file = db.Column(db.String(120)) 
    profile_photo = db.Column(db.String(120)) 
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    is_active = db.Column(db.Boolean, nullable=False, default=True)

class Job(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    location = db.Column(db.String(100), nullable=False)
    experience = db.Column(db.String(50), nullable=False, default='Entry level', server_default='Entry level')
    job_type = db.Column(db.String(50), nullable=False, default='Full-time')
    job_role = db.Column(db.String(50), nullable=False, default='General')
    description = db.Column(db.Text, nullable=False)
    salary = db.Column(db.String(50), nullable=False)  
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    is_open = db.Column(db.Boolean, nullable=False, default=True)
    recruiter = db.relationship('User', foreign_keys=[user_id])
    question_sets = db.relationship('InterviewQuestionSet', backref='job', lazy=True)


class InterviewQuestionSet(db.Model):
    __tablename__ = 'interview_question_sets'
    id = db.Column(db.Integer, primary_key=True)
    job_id = db.Column(db.Integer, db.ForeignKey('job.id'), nullable=False)
    questions = db.Column(db.Text, nullable=False, default='[]')
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    is_active = db.Column(db.Boolean, nullable=False, default=True)

class Application(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    job_id = db.Column(db.Integer, db.ForeignKey('job.id'), nullable=False)
    resume_id = db.Column(db.Integer, nullable=True)
    submitted_resume = db.Column(db.String(255), nullable=True)
    cover_note = db.Column(db.Text)
    message = db.Column(db.Text, nullable=False, default='')
    ai_score = db.Column(db.Float, default=0.0)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    status = db.Column(db.String(20), nullable=False, default='Applied')
    status_history = db.Column(db.Text, nullable=True)
    recruiter_notes = db.Column(db.Text, nullable=True)
    recruiter_notes_visible = db.Column(db.Boolean, nullable=False, default=False)
    interview_access = db.Column(db.String(20), nullable=False, default='pending')

    user = db.relationship('User', backref=db.backref('applications', lazy=True))
    job = db.relationship('Job', backref=db.backref('applications', lazy=True))

    __table_args__ = (db.UniqueConstraint('user_id', 'job_id', name='unique_user_job_application'),)

class Interview(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    application_id = db.Column(db.Integer, db.ForeignKey('application.id'), nullable=False)
    interviewer_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    interview_type = db.Column(db.String(30), nullable=False, default='Video')
    interview_round = db.Column(db.String(50), nullable=False, default='Screening')
    scheduled_at = db.Column(db.DateTime, nullable=False)
    duration_minutes = db.Column(db.Integer, nullable=False, default=45)
    meeting_link = db.Column(db.String(500))
    interviewer_names = db.Column(db.String(500))
    scheduled_timezone = db.Column(db.String(80), nullable=True)
    notes = db.Column(db.Text)
    notes_visible = db.Column(db.Boolean, nullable=False, default=False)
    status = db.Column(db.String(20), nullable=False, default='Scheduled')
    decision = db.Column(db.String(20))
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)
    question_set_id = db.Column(db.Integer, db.ForeignKey('interview_question_sets.id'), nullable=True)
    access_granted_at = db.Column(db.DateTime, nullable=True)
    started_at = db.Column(db.DateTime, nullable=True)
    completed_at = db.Column(db.DateTime, nullable=True)
    responses = db.Column(db.Text, nullable=True)
    ai_scores = db.Column(db.Text, nullable=True)
    overall_score = db.Column(db.Float, nullable=True)

    application = db.relationship('Application', backref=db.backref('interviews', lazy=True))
    interviewer = db.relationship('User', foreign_keys=[interviewer_id])
    feedback = db.relationship('InterviewFeedback', backref='interview', uselist=False, cascade='all, delete-orphan')
    question_set = db.relationship('InterviewQuestionSet', backref='interviews')

class InterviewFeedback(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    interview_id = db.Column(db.Integer, db.ForeignKey('interview.id'), nullable=False, unique=True)
    technical_skills = db.Column(db.Integer, nullable=False)
    communication = db.Column(db.Integer, nullable=False)
    problem_solving = db.Column(db.Integer, nullable=False)
    overall_rating = db.Column(db.Integer, nullable=False)
    comments = db.Column(db.Text, nullable=False)
    recommendation = db.Column(db.String(20), nullable=False)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
